userspace/files/fstab

First part of #11. Android mounts both of these as RO.
There's also systemd mount targets for these partitions in `agnos-base_0.0.1.deb` that should be removed.

mount /dsp and /firmware read only

---

userspace/home/.config/htop/htoprc

AGNOS has no default `htoprc` at this time. Add one with several handy settings from the `htoprc` that ships with NEOS:
- Default to process tree view
- Show kernel threads
- Add the column for currently assigned CPU
- Count CPUs from zero instead of one
This config is identical to the NEOS version except for the left/right column config due to the extra CPUs.

improved default htop config

---

userspace/files/weston.service

Silences a bunch of INFO message when starting the ui. There are a lot when using the no copy NV12 textures.
```
GBM_INFO::msmgbm_bo_import_gbm_buf(1161):: MAP table is empty
GBM_INFO::msmgbm_bo_import_gbm_buf(1164)::Registered fd=20 to table
GBM_INFO::get_size(371):: VENUS_BUF_SIZE=4804608, computed for Width=1928, Height=1208
GBM_INFO::get_size(371):: VENUS_BUF_SIZE=4804608, computed for Width=1928, Height=1208
GBM_INFO::msmgbm_get_metadata(2588)::metadata_fd=-1 and hence valid meta info cannot be retrieved
GBM_INFO::msmgbm_get_metadata(2589)::We will make a graceful exit
GBM_INFO::msmgbm_get_metadata(2588)::metadata_fd=-1 and hence valid meta info cannot be retrieved
GBM_INFO::msmgbm_get_metadata(2589)::We will make a graceful exit
GBM_INFO::msmgbm_bo_cpu_map(1796)::This is not …
```

Set GBM debug level

---

build_kernel.sh

Kernel boot time goes from 10s -> 5.9s with `quiet` -> 3.6s with `quiet` + `loglevel=3`.

set quiet kernel param

---

userspace/debs/agnos-wlan_0.0.1.deb
userspace/debs/agnos-wlan_0.0.2.deb
userspace/hardware_setup.sh
userspace/usr/comma/wait_for_file.sh

The issue this fixes is that `rmt_storage` needs to have these symlinks existing before starting, which are populated by udev and `/etc/udev/scripts/automountsdcard.sh`:
- /dev/block/bootdevice/by-name/modemst1
- /dev/block/bootdevice/by-name/modemst2
- /dev/block/bootdevice/by-name/fsc
- /dev/block/bootdevice/by-name/fsg
Not sure if there's a cleaner way than this, but couldn't figure out how to easily wait for a file to exist before starting a service other than this bash script called in `ExecStartPre=`

Wait for partitions before starting rmt_storage service

---

userspace/motd/20-quickstart

configured away from the default of ctrl-b

note that tmux prefix key is backtick in MOTD

---

Dockerfile.agnos
build_kernel.sh
build_system.sh
load_kernel.sh
load_kernel_headers.sh
userspace/base_setup.sh
userspace/files/serial-hostname.service
userspace/services.sh
userspace/usr/comma/set-hostname.sh

This even allows using `hostnamectl` to change the hostname (although it changes back to serial number on reboot)
```sh
comma@tici-d62c206c:/data/openpilot$ hostnamectl 
Static hostname: tici-d62c206c
Icon name: computer
Machine ID: 0e56b517e1dbc6ffa9481f7263f690e5
Boot ID: b86719b5f5904aeeab49a8e89ea8abdf
Operating System: Ubuntu 20.04.5 LTS
Kernel: Linux 4.9.103+
Architecture: arm64
comma@tici-d62c206c:/data/openpilot$ nmcli general hostname
tici-d62c206c
```
Note that the following alternative approaches do not work:
* `hostnamectl set-hostname --transient <new-host-name>` because `NetworkManager` doesn't respect a pre-existing transient hostname.
* `nmcli general hostname <new-host-name>` because it seems impossible to hook it after `NetworkManager` is up and before it brings up …

hostname with serial number

---

userspace/files/ssh-param-watcher.service

Having both `After=multi-user.target` and `WantedBy=multi-user.target` doesn't sound like a good idea:
https://unix.stackexchange.com/questions/693485/after-multi-user-target-and-others-not-working-in-a-systemd-service
Also, the rescue target is nicer, since that make s sure sshd is up in case any of the runlevel 2 stuff fails.

Start sshd early

---

userspace/files/sshd_config

Our traffic control routing consists of a parent `mq` qdisc that encompasses 5 hardware tx queues with a `pfifo_fast` attached to each. `pfifo_fast` is supposed to prioritize interactive traffic using the ToS/DSCP field, but it is unclear why it does not seem to prevent serious ssh stability issues when the device is uploading a file on a slow network.
I am guessing that we are saturing the one hardware queue we are currently using, making the `pfifo_fast` useless as it can't stuff any more interactive ssh packets into the single hardware queue as it waits for the file packets to send.
Running a speed test, both traffic goes out on one hardware queue (`parent :3`):
```bash
comma@comma-d7e84c3:/data/openpilot$ sudo tc -s qdisc ls dev wlan0
qdisc mq 0: root 
Sent 158247322 bytes 154641 pkt …
```

Improve ssh responsiveness on slow Wi-Fi networks

---

build_system.sh

For some reason on an M2 Mac with OrbStack registering qemu messes up the `build_system.sh` script. But on an `arm64` native Ubuntu (Khadas Edge2) works fine even with qemu registered.
Same changes proposed and already exist in https://github.com/commaai/agnos-builder/pull/231

Fixed incorrectly registering qemu on Apple silicon

---

Dockerfile.agnos

Switch to `MAKEFLAGS="-j$(nproc)"` for pyqt5 to avoid OOMs

Reduce memory usage when building system

---

userspace/openpilot_python_dependencies.sh

resolves https://github.com/commaai/agnos-builder/issues/240
openpilot_python_dependencies.sh has been setup to use uv. Dockerfile.agnos still uses pyenv which can also be switched to use uv.

switch pyenv to uv

---

userspace/pyproject.toml
userspace/uv.lock

openpilot doesnt compile with the latest agnos master. The following changes make it work again.
- Re-enable pyopencl
- Downgrade numpy
- Add future-fstrings

Fix python dependencies

---

.github/workflows/build.yaml
build_system.sh

For https://github.com/commaai/agnos-builder/issues/230:
|Step|No cache|Cache|
| :---:        |    :----:   |          :---: |
|kernel|7min|3min*|
|system|33min|2min**|
|upload system image|4min|4min|
\* takes 3min with ccache - on my computer is much faster - caching the `out` folder doesn't make any difference - I assume this is because the absolute path where the kernel is built always changes between runs
\** depends a lot on what docker layers the changes have been made - if the change is on the first layers, it takes longer - if it's on the last layers, it takes less

CI: add system build

---

Dockerfile.sparsify
build_system.sh

useradd will fail if the host user has uid:gid 1000:1000. 
Fix: Delete user in container if the uid:gid is the same and only then create a new user with the same user name as the host user.

Fix image creation docker workflow in host ubuntu

---

tools/edl

This is a temporary fix until capstone `v5.0.2` is [released](https://github.com/capstone-engine/capstone/issues/2301).

Fixed edl capstone issue on M-series macs

---

.github/workflows/build.yaml

This is a more battle tested version I tested in a separate [repo](https://github.com/andiradulescu/debug-github-actions-commit-message).
The scope of `Get commit message` is for the `[upload]` tag in commit messages.

CI: update get commit message

---

Dockerfile.agnos

For some reason (might be a `uv` bug), `uv pip install --no-cache-dir --system .` that is ran in `/tmp` also moves all other files from `tmp` to `site-packages` https://github.com/commaai/agnos-builder/issues/225#issuecomment-2248783245.
With this PR I'm running it from an empty folder just with `pyproject.toml` and `uv.lock` inside.
- system.img is back to 4.26 GB from 4.67 GB
- system.img artifact 1.21 GB from 1.59 GB
AGNOS boots fine and `site-packages` is clean again:

uv pip install in a separate tmp folder

---

userspace/usr/comma/comma.sh

I use [Cursor](https://www.cursor.com) instead of VSCode and on every boot (or AGNOS reflash) I need to link `.cursor-server`.
It uses the same temporary `vscode-server` directory.

support cursor server (vscode fork)

---

.github/workflows/build.yaml

Now since there are no other private submodules, we can let `actions/checkout` pull `agnos-kernel-sdm845` which is much faster since it's with `--depth=1` vs `build_kernel.sh` which clones the whole repo.

also checkout submodules

---

flash_kernel.sh
flash_system.sh

- moving to `system.img` from `system-skip-chunks.img` (in order to remove `system-skip-chunks.img` later)
- `flash_kernel.sh` with `flash_system.sh` always flashes the active slot

update flash scripts to always flash active slot

---

Dockerfile.agnos

Fix the following warnings when building the docker container:
WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match

Fix FromAsCasing warning

---

Dockerfile.agnos
build_system.sh

Including the `qemu-aarch64-static` and `qemu-arm-static` binaries is not necessary, if `docker run --rm --privileged multiarch/qemu-user-static --reset -p yes` is executed before building the docker image. Only running it for x86_64 machines also fixes the `InvalidBaseImagePlatform ` warning.

Fix InvalidBaseImagePlatform warning on aarch64

---

Dockerfile.agnos

Address SecretsUsedInArgOrEnv warning
Secrets should not be saved in environment variable as they will be available also on the device. In this case they are anyway known and not critical, but they are not even used in the build process or later on the device. So IMHO better to remove them completely.

Fix SecretsUsedInArgOrEnv warning

---

Dockerfile.agnos
userspace/base_setup.sh
userspace/compile-modemmanager.sh
userspace/install_extras.sh
userspace/openpilot_dependencies.sh

Use apt-fast instead of apt-get. This will speed up the build process especially when the apt package downloads are slow.

Replace apt-get with apt-fast

---

Dockerfile.agnos
userspace/compile-pyqt5.sh

Build PyQt5 wheel in parallel to other compilation steps and install from wheel later.
This reduces the overall Docker build time and makes better use of the Docker build cache.
Tests: Builds and runs on C3. Openpilot compiles, GUI works. (Not tested on-road)

Build PyQt5 wheel in parallel

---

Dockerfile.builder
build_system.sh

Missed a `\` in `$DIR/tools/simg2dontcare.py \$TMP_SPARSE \$TMP_SKIP;` and also did some cleanup.
Testing to see it works fine locally, since CI has some hiccup.

image creation cleanup

---

Dockerfile.agnos
userspace/files/serial-getty@ttyMSM0_override.conf

In Ubuntu 24.04 (systemd 255) and Kernel 4.9 the boot console is not properly hung up before the start of serial-getty@ttyMSM0. In this state, kernel messages will continue to be printed to the serial console.
By sending another hupcl (Hang Up on Close) using stty, we can force the hangup and kernel messages will be properly handled by systemd and written to the appropriate log files without appearing on screen. 
This fixes #319.

Hang up console before serial-getty start

---

userspace/files/comma.service

openpilot processes never have a chance to react to reboot or shutdown since we send SIGKILL first. This adopts the [default behavior](https://www.freedesktop.org/software/systemd/man/latest/systemd.kill.html) of a SIGTERM first, wait a timeout, then a SIGKILL
For https://github.com/commaai/openpilot/pull/32103

kill: send SIGTERM first

---

Dockerfile.agnos
userspace/uv/pyproject.toml
userspace/uv/uv.lock

`uv sync` by default removes extraneous packages from the environment (e.g. pip). And for some reason it now ignores [UV_PROJECT_ENVIRONMENT](https://docs.astral.sh/uv/concepts/projects/#configuring-the-project-environment-path). Better just stick with `uv pip install`.
Separately, adding `openpilot[dev]` for some reason breaks `uv`. Tried not to spend much time on this.

don't use uv sync for system environment

---

Dockerfile.agnos

This is used for panda. Tried switching building panda with clang, but takes more time to make it work than this. Plus this seems safer than changing the compiler.
\- ~200MB

remove unused gcc-arm-none-eabi architectures & bins

---

userspace/motd/10-header

```
.~ssos+.
+8888888888i,
{888888888888o.
h8888888888888k
t888888888s888k
`t88888d/ h88k
```    h88l
,88k`
.d8h`
+d8h
_+d8h`
;y8h+`
|-`
Welcome to AGNOS ade422af2aad05eaf352db766ec1aa53d9b95243
Based on Ubuntu 24.04.1 LTS (GNU/Linux 4.9.103 aarch64)
Here are some useful commands:
Enter the tmux session where the comma service runs
(note: tmux prefix key has been configured to backtick)
└── tmux a
Install Ubuntu packages
└── sudo apt update && sudo apt install <pkg>
Install Python packages
└── pip install <pkg>
When modifying AGNOS, keep in mind that the system partition isn't
particularly large. /data/ is the largest partition, and unlike the
rest of the partitions, it will persist across AGNOS updates.
Want a clean slate? Reflash AGNOS with https://flash.comma.ai.
```

Include AGNOS version in motd header

---

Dockerfile.agnos
userspace/compile-pyqt5.sh

Enable ccache for compilation. This should speed up the overall build by ~50%.
The cache is stored in individual docker cache mounts per package, which are concurrently accessible by different runners.

Use ccache to speed up compilation

---

build_system.sh

Explicitly set platform to linux/arm64. Without this linux/amd64 is used on amd64 systems, leading to a build failure.
Fixes https://github.com/commaai/agnos-builder/issues/370

Fix build on amd64 systems

---

userspace/base_setup.sh

Resolves https://github.com/commaai/agnos-builder/issues/318
- removes chrony and replaces it with [systemd-timesyncd](https://wiki.archlinux.org/title/Systemd-timesyncd)
- makes time syncing faster than chrony and when network configuration or connectivity changes
- installed build and tested both with internet and without internet on boot - time is synced almost instantly after network connectivity is up
```
$ journalctl -u systemd-timesyncd
Aug 08 14:51:13 comma systemd[1]: Starting systemd-timesyncd.service - Network Time Synchronization...
Aug 08 14:51:13 comma (imesyncd)[2819]: systemd-timesyncd.service: ProtectHostname=yes is configured, but the kernel does not support UTS na>
Aug 08 14:51:13 comma systemd[1]: Started systemd-timesyncd.service - Network Time Synchronization.
Aug 08 …
```

replace chrony with timesyncd

---

userspace/usr/comma/comma.sh

Resolves https://github.com/commaai/agnos-builder/issues/339
Alternative (by mounting to `/tmp` variant):
```
rm -rf /data/tmp
ln -s /tmp /data/tmp
```
Tested both variants on device by editing `/usr/comma/comma.sh` manually, touching some files in `/data/tmp` then restart and investigate the results.

clear /data/tmp on boot

---

Dockerfile.agnos
userspace/uv/openpilot/pyproject.toml
userspace/uv/pyproject.toml
userspace/uv/uv.lock

Synced from https://github.com/commaai/openpilot/pull/33570

add missing python dev dependencies

---

scripts/download-from-manifest.py

https://discord.com/channels/469524606043160576/871838269405556736/1288752129594359860
output is expected to exist but isn't on a fresh clone.

Ensure parent directories exist for download-from-manifest.py

---

README.md

when wanting to run `build_system.sh` i run into this error:
```bash
└─(13:31:34 on master)──> ./build_system.sh                                                                                                            ──(Fri,Nov08)─┘
unknown flag: --check
See 'docker buildx build --help'.
```
This comes from having docker buildx 0.14.0:
```bash
─(13:34:24 on master)──> docker buildx version                                                           ──(Fri,Nov08)─┘
github.com/docker/buildx v0.14.0-desktop.1 7b0470cffd54ccbf42976d2f75febc4532c85073
```
After looking through the discord it was mentioned that `0.15.0` docker buildx is necessary since it includes the missing `--check` flag: https://discord.com/channels/469524606043160576/1262118077017882715/1271548206198820865
This was a bit …

`docs`: add mention of docker-buildx `>0.15.0` requirement

---

Dockerfile.agnos
userspace/openpilot_python_dependencies.sh

The uv error comes from the recent changes to the directory path. This updates the path while also addressing another error that occurs due to missing pkgconfigs with python 3.12
uv error:
```sh
------                                                                                                                                                                                                                    
> [agnos-base 10/12] RUN /tmp/agnos/openpilot_python_dependencies.sh:                                                                                                                                                    
0.094 installing uv... …
```

`build_system`: fix uv `5.1` error and `3.12` pkgconfig error

---

userspace/home/.tmux.conf

dividing by 1000 is necessary since in unix systems the temperature is given to us in millidegrees (Celsius)
https://developer.toradex.com/software/linux-resources/linux-features/temperature-sensor-linux/?t#nxpfreescale-imx-6-based-modules
seemed helpful to include since it was mentioned in this issue https://github.com/commaai/agnos-builder/issues/405

add GPU temp to tmux info bar

---

userspace/usr/comma/sound/amplifier.py

Fix sound 

---

Dockerfile.agnos
userspace/uv/pyproject.toml
userspace/uv/uv.lock

Although in CI it passes just fine, when attempting to build the image on my machine we run into this error:
```sh
#41 0.190 warning: Missing version constraint (e.g., a lower bound) for `dbus-python`
#41 0.190 warning: Missing version constraint (e.g., a lower bound) for `evdev`
#41 0.190 warning: Missing version constraint (e.g., a lower bound) for `smbus2`
#41 0.190 warning: Missing version constraint (e.g., a lower bound) for `ipython`
#41 0.190 warning: Missing version constraint (e.g., a lower bound) for `pyrasite`
#41 0.190 warning: Missing version constraint (e.g., a lower bound) for `py-spy`
#41 2.504   × Failed to download and build `aiortc==0.9.27`
#41 2.504   ╰─▶ Build backend failed to determine metadata through
#41 2.504       `prepare_metadata_for_build_wheel` (exit status: …
```

Revert "add some debugging python packages"

---

README.md

Was running into issues with `./flash_system.sh` until running into this [Discord message](https://discord.com/channels/469524606043160576/1263672324973138033/1264961677024038923) which led me to finding instructions within `./flash_system.sh`
The error:
```sh
└─(22:53:12 on fix-system-build-errors ✹)──> ./flash_system.sh            
Checking active slot...
Traceback (most recent call last):
File "/Volumes/agnos/agnos-builder/tools/edl_repo/edl", line 393, in <module>
base.run()
File "/Volumes/agnos/agnos-builder/tools/edl_repo/edl", line 290, in run
conninfo = self.doconnect(loop)
File "/Volumes/agnos/agnos-builder/tools/edl_repo/edl", line 200, in doconnect
self.cdc.connected = self.cdc.connect(portname=self.portname)
File "/Volumes/agnos/agnos-builder/tools/edl_repo/edlclient/Library/Co …
```

`docs`: improve flashing device section

---

userspace/files/comma.service

Follow up to https://github.com/commaai/agnos-builder/pull/228, not sure why I misunderstood the parameters. Re-reading https://www.freedesktop.org/software/systemd/man/latest/systemd.kill.html and https://www.freedesktop.org/software/systemd/man/latest/systemd.service.html makes it clear that only the delay is required

Remove redundant comma service parameters

---

.github/workflows/push-and-comment.yaml

noticed the constant emails that I would receive when pushing to my PRs. Did some investigating and found that it was due to `push-and-comment` attempting to download artifacts from `build.yaml`. However we only expect an artifact when the commit message contains `[upload]`
This added check will prevent the job from running if it does not contain `[upload]`

fix noisy `push-and-comment` workflow

---

userspace/files/weston.service

4s boot time savings, solves #445
---
Before:
```
comma@comma-5e2e507b:/$ systemd-analyze critical-chain weston.service
The time when unit became active or started is printed after the "@" character.
The time the unit took to start is printed after the "+" character.
weston.service +368ms
└─systemd-user-sessions.service @8.381s +37ms
└─network.target @8.355s
└─NetworkManager.service @4.766s +3.588s
└─dbus.service @4.520s +206ms
└─basic.target @4.494s
└─sockets.target @4.494s
└─lxd-installer.socket @4.472s +21ms
└─sysinit.target @4.452s
└─systemd-resolved.service @4.050s +401ms
└─systemd-tmpfiles-setup.service @3.952s +93ms
└─local-fs.target @3.944s
└─config.mount @8.457s
└─local-fs-pre.target @876ms
└─keyboard-setup.service @622ms +254ms
└─systemd-journald.socket @598ms
└─system.slice …
```

Unblock weston on networking

---

userspace/compile-qtwayland5.sh

This fixes the main ui crashing immediately on startup.
```
#0  0x0000000000000000 in ?? ()
#1  0x0000007fb1179500 in ?? () from /usr/lib/aarch64-linux-gnu/qt5/plugins/platforms/libqwayland-egl.so
```
The reason is `checkinstall` doesn't package all the files in `compile-qtwayland5.sh` corectly because of [qmake](https://askubuntu.com/a/1017594/562170), so I replaced it with `dpkg-deb` (which is also used in `build-qt-deb.sh` and `build-libwayland-deb.sh`).
I have no idea how it worked before. Since the `qtwayland5` repo/branch we are using didn't change and neither the `checkinstall` version. Checking `libqwayland-egl.so` on AGNOS v11.10 the file was provided by `qtwayland5` (correctly), so something changed recently.
The `checkinstall` errors were `silent` so this is why the build …

compile-qtwayland5.sh without checkinstall

---

userspace/openpilot_dependencies.sh

the Qt X backend does not start up due to missing dependencies:
```
QT_DEBUG_PLUGINS=1 QT_QPA_PLATFORM=xcb selfdrive/ui/ui
...
: QLibraryPrivate::loadPlugin failed on "/usr/lib/aarch64-linux-gnu/qt5/plugins/platforms/libqxcb.so" : "Cannot load library /usr/lib/aarch64-linux-gnu/qt5/plugins/platforms/libqxcb.so: (libxcb-xinput.so.0: cannot open shared object file: No such file or directory)"
: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
```
so, adding missing shared objects for x backend:
```
comma@comma-bb546e42:/data/openpilot$ ldd /usr/lib/aarch64-linux-gnu/qt5/plugins/platforms/libqxcb.so  | grep 'not found'
libxcb-xinput.so.0 => not found
libxcb-icccm.so.4 => not found
libxcb-image.so.0 => not …
```

feat: support starting openpilot in an X virtual server

---

userspace/base_setup.sh
userspace/compile-ffmpeg.sh

required for running clips on device
other blockers are still there (like replay, selfdrive/ui, ffmpeg optimizations), but we at least need ffmpeg to support x264 encoding
getting in now since new AGNOS release is very soon: https://github.com/commaai/agnos-builder/pull/472#issuecomment-2889267793
```bash
./build_system.sh
./flash_system.sh
```
```bash
comma@comma-bb546e42:/data/openpilot$ ffmpeg
ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers
built with gcc 13 (Ubuntu 13.3.0-6ubuntu2~24.04)
configuration: --enable-gpl --enable-libx264 --enable-shared --disable-static --disable-htmlpages
libavutil      56. 31.100 / 56. 31.100
libavcodec     58. 54.100 / 58. 54.100
libavformat    58. 29.100 / 58. 29.100
libavdevice    58.  8.100 / 58.  8.100
libavfilter     7. 57.100 / …
```

feat: build ffmpeg with libx264 support
