userspace/files/serviceproviders.xml
More info here:
https://www.swan.sk/media/content/Ako_zistit_dostupnost_siete_a_nastavit_vlastne_zariadenie.pdf
"4. APN je potrebné nastaviť na "internet" (bez úvodzoviek).
5. MCC je potrebné mať nastavené na 231.
6. MNC nastaviť na 03."
=> APN/MCC/MNC for Slovakia Swan (4ka) operator 

tools/extract_tools.sh
* detect git lfs installation
* detect git lfs objects that need to be pulled using `git lfs ls-files` command. `! -f` doesn't work because it returns true for lfs pointer files as well.
=> extract_tools.sh: detect LFS installation + fix pull detection

userspace/openpilot_python_dependencies.sh
=> update python to 3.8.10

userspace/debs/agnos-base.deb, userspace/debs/agnos-base_0.0.1.deb, userspace/files/fstab, userspace/files/ssh_override.conf, userspace/files/sshd_config, userspace/hardware_setup.sh
Needs testing. Should also remove the systemd mount target in `agnos-base_0.0.1.deb`.
=> mount /persist as read only

userspace/files/fstab
=> mount userdata with noatime

userspace/files/fstab, userspace/files/mount_storage.service, userspace/services.sh, userspace/usr/comma/mount-storage.sh
=> mount sd card

userspace/usr/comma/comma.sh
=> VSCode remote support

userspace/files/serial-hostname.service, userspace/services.sh, userspace/usr/comma/set-hostname.sh
=> set hostname to tici-<serial_number>

userspace/home/.bash_profile
=> "cd /data/openpilot" only for main tmux session

build_kernel.sh, internal/README.md, internal/ota_push.sh, internal/package_ota.sh, userspace/files/weston.service, userspace/usr/comma/comma.sh
=> XBL + ABL updates

scripts/setup-on-device.sh, userspace/files/comma.service, userspace/files/set_time.service, userspace/files/weston-ready.service, userspace/services.sh, userspace/usr/comma/comma.sh
=> ensure comma service always run

internal/README.md
* ABL factory reset timeout
* more display support
=> new bootloaders

internal/ota_push.sh, internal/package_ota.sh
=> cleanup package scripts

flash_system.sh, tools/simg2dontcare.py
related https://github.com/commaai/provisioning/pull/381
=> add simg2dontcare.py

userspace/poetry.lock, userspace/pyproject.toml
add pytest-cpp and pytest-timeout for jenkins
=> userspace: add pytest packages

userspace/files/ssh-param-watcher.service
My proposal for fixing ssh on boot. Building another image to test.
=> Start ssh early

userspace/base_setup.sh
currently building an image. standby.
=> Remove pkgs and refactoring

Dockerfile.sparsify, README.md, build_system.sh
For https://github.com/commaai/agnos-builder/issues/237
Fixes some issue with macOS sparsify and some nice to haves.
=> Fix build system in docker on macOS

.github/workflows/tests.yaml
Created a PR in response to: https://github.com/commaai/agnos-builder/issues/255
=> updating setup-python@v4 to v5 in tests.yaml

.github/workflows/build.yaml, .github/workflows/push-and-comment.yaml
Tested, works fine.
To show the full hash in the comment it needs to be between commas: "30a7fcb89e9e5f8398c16ced7ae08626f68a3e91".
=> ci: update VERSION to commit hash for pull requests

build_kernel.sh, build_kernel_headers.sh, build_system.sh, flash_all.sh, flash_kernel.sh, flash_system.sh, load_kernel.sh, load_kernel_headers.sh, scripts/bootchart.sh, scripts/check-space.sh, scripts/kernel_faddr2line.sh, scripts/ota_push.sh, scripts/pull_ota.sh, scripts/setup-on-device.sh, scripts/shell.sh, tools/edl, tools/extract_tools.sh
Mostly for macOS.
A good explaination [here](https://stackoverflow.com/a/58494728/639708).
Same thing for:
- openpilot https://github.com/commaai/openpilot/pull/33111
- panda https://github.com/commaai/panda/pull/1987
\* left `userspace` alone, for now, since it only runs on device
=> update bash scripts to #!/usr/bin/env bash

userspace/pyproject.toml, userspace/uv.lock
CI devices fail in https://github.com/commaai/openpilot/pull/33442 
See these [logs](https://jenkins.comma.life/blue/organizations/jenkins/openpilot/detail/pytest_warnings/1/pipeline#step-212-log-117)
Will need to install it manually for now
=> add pytest-asyncio python package

.github/workflows/build.yaml, build_system.sh
CI VERSION is now e.g. "11-f439f1a"
=> Nicer version for CI builds

build_system.sh
=> Smaller image size

userspace/uv/openpilot/pyproject.toml, userspace/uv/pyproject.toml, userspace/uv/uv.lock
- "evdev" - needed for phantom_touch_logger.py
- "smbus2" - needed for amplifier.py
- "inputs" - needed for joystickd, synced from openpilot
=> Add missing evdev, smbus2 and inputs

Dockerfile.agnos, userspace/compile-rep_ren.sh
Build and package rep and ren from sources.
For https://github.com/commaai/agnos-builder/issues/380
=> Install rep and ren

Dockerfile.agnos
Fixes https://github.com/commaai/agnos-builder/issues/374
Tested on device.
=> fix fstab warning

userspace/usr/comma/sound/sound_init.sh
Haven't repro'd yet, but possible fix for #385
=> sound_init: wait for tinymix controls

Dockerfile.agnos, build_system.sh
=> compile bytecode for python packages

userspace/files/01-network-manager-all.yaml, userspace/files/ethernet.yaml
=> use NetworkManager for all devices

Dockerfile.agnos
Was poking around comma for fun, noticed this typo in the Dockerfile, cheers.
=> Fix typo in Dockerfile.agnos

userspace/files/comma.service
Closes https://github.com/commaai/agnos-builder/issues/426
=> systemd: configure comma service to allow start/stop

Dockerfile.agnos, userspace/files/profile, userspace/openpilot_python_dependencies.sh
picking up from https://github.com/commaai/agnos-builder/pull/428
=> Use system python 3.12

userspace/usr/comma/set_adb.sh
=> add gadget directory check in `disabling adb`

build_system.sh
Gets the boot time hit down to ~0.5s for going from 750MB -> 1.1GB
=> Switch to gzip'd squash

scripts/build_userdata.sh
Run `img2simg` in docker + reduce memory usage to 90GB
=> improve userdata build

build_kernel.sh
https://github.com/commaai/openpilot/pull/34558
=> Realtime, for real this time

Dockerfile.agnos, userspace/files/allow-modem-control.pkla, userspace/files/allow-network-control.pkla, userspace/files/comma-polkit.rules
Partially closes https://github.com/commaai/openpilot/issues/35707, there is another leak that occurs even with no rules active.
polkitd has a compat rule file for legacy pkla files which we use, however there appears to be a leak of a few KB when [spawning a new process](https://www.freedesktop.org/software/polkit/docs/0.106/polkit.8.html), which is what the compat rule does.
I ran `HARDWARE.get_modem_temperatures()` at ~10-20 Hz (as fast as possible), normally `hardwared` runs this every 10 seconds. Memory usage for `/usr/lib/polkit-1/polkitd --no-debug`:
- master AGNOS: 32,444 KB (21:29 min)
- this PR: 54,176 KB (20:00 min) ???
```js
comma@comma-50194f77:/usr/share/polkit-1/rules.d$ cat 49-polkit-pkla-compat.rules 
polkit.addAdminRule(function(action, subject) {
//polkit.log('Starting …
```
=> Remove deprecated pkla files

userspace/files/agnos-debug.service, userspace/services.sh, userspace/usr/comma/debug.py, userspace/usr/comma/fs_setup.sh
This should share more with openpilot's bootlog but this is a good start.
=> persistent boot debug logs
